controllers:
    resource: ../src/Controller/
    type: attribute


index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_agenda'
        permanent: true
        keepQueryParams: true